// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGeKO4uMNSOXHQzK7RjLfv7FYKcyX4wdI',
    appId: '1:488151937611:web:d4b76a6edfe4950f7753ce',
    messagingSenderId: '488151937611',
    projectId: 'pokedex-tcg-bee6b',
    authDomain: 'pokedex-tcg-bee6b.firebaseapp.com',
    storageBucket: 'pokedex-tcg-bee6b.firebasestorage.app',
    measurementId: 'G-9J42G3HEGW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhqERe_mPgcrEZzuSg6VIXKYeRwFwA8mo',
    appId: '1:488151937611:android:7117864c2383ea277753ce',
    messagingSenderId: '488151937611',
    projectId: 'pokedex-tcg-bee6b',
    storageBucket: 'pokedex-tcg-bee6b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKRbfcXE8vsGLNE5KlmJePzuqylw0oDIU',
    appId: '1:488151937611:ios:3868d6b9ecec137f7753ce',
    messagingSenderId: '488151937611',
    projectId: 'pokedex-tcg-bee6b',
    storageBucket: 'pokedex-tcg-bee6b.firebasestorage.app',
    iosBundleId: 'com.example.pokedexTcg',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKRbfcXE8vsGLNE5KlmJePzuqylw0oDIU',
    appId: '1:488151937611:ios:3868d6b9ecec137f7753ce',
    messagingSenderId: '488151937611',
    projectId: 'pokedex-tcg-bee6b',
    storageBucket: 'pokedex-tcg-bee6b.firebasestorage.app',
    iosBundleId: 'com.example.pokedexTcg',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGeKO4uMNSOXHQzK7RjLfv7FYKcyX4wdI',
    appId: '1:488151937611:web:67f22760c89e42f37753ce',
    messagingSenderId: '488151937611',
    projectId: 'pokedex-tcg-bee6b',
    authDomain: 'pokedex-tcg-bee6b.firebaseapp.com',
    storageBucket: 'pokedex-tcg-bee6b.firebasestorage.app',
    measurementId: 'G-V496SD6FZK',
  );
}
